version: '3.8'
services:
  frontend:
    # Step 5.1 - Point build step to the client directory
    build:  ./frontend

    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    
    depends_on:
      - backend
    networks:
      - mern-network


  backend:
   
    build: ./backend

    container_name: backend_c
    restart: always
    ports:
      - "3260:3260"    
    volumes:
      - ./backend:/app
      - ./app/node_modules   
    depends_on:
      - mongo
    networks:
      - mern-network




  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongodb_c
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:c:data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
        

